version: '3'
services:
  mysql:
    restart: always
    container_name: mysql
    image: mysql
    volumes:
      - ./docker-scripts:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: password
      SPRING_DATASOURCE_URL: jdbc:mysql://127.0.0.1:3306/flexibility?zeroDateTimeBehavior=convertToNull
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - 3306:3306

  flexibility:
    restart: on-failure
    build: ./
    expose:
      - 8080
    ports:
      - 8080:8080
    environment:
      WAIT_HOSTS: mysql:3306
    depends_on:
      - mysql