version: "3"
services:
  server:
    image: examen
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/payments?useSSL=false
    networks:
      - springmysql-net
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:5.7
    networks:
      - springmysql-net
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=payments
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password

networks:
  springmysql-net: