version: "3.9"
services:
  db:
    platform: linux/x86_64
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: payments
    ports:
      - 3306:3306