version: '3'

services:
  mysql-docker-container:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=payments
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    ports:
      - 3306:3306
    volumes:
      - /data/mysql
      
  spring-boot-jpa-app:
    image: spring-boot-jpa-image
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-docker-container:3306/payments?zeroDateTimeBehavior=convertToNull
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mysql-docker-container
    ports:
      - 8087:8080
    volumes:
      - /data/spring-boot-app
