FROM openjdk:8-jdk-alpine

LABEL maintainer="jonathanariel94@gmail.com"
LABEL version="0.1.0"
LABEL LABEL description="Flexibility Exam"

RUN addgroup -S spring && adduser -S spring -G spring

USER spring:spring

ARG JAR_FILE=target/*.jar
COPY ${JAR_FILE} app.jar

ENTRYPOINT ["java","-jar","/app.jar"]