version: '3.1'
services:
  app:
    container_name: app-springboot-postgresql
    image: app-springboot-postgresql
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - dbpostgresql
  dbpostgresql:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - DATABASE_HOST=dbpostgresql
      - DATABASE_PORT=5432
      - DATABASE_NAME=mydb
      - POSTGRES_HOST_AUTH_METHOD=trust

       