version: '3.6'

services:
  db:
    image: mysql
    ports:
      - "3306:3306"
    restart: always
    env_file:
      - .db.env
    volumes:
    - "./data:/var/lib/mysql"
  web:
    build: .
    ports:
    - "8080:8080"
    depends_on:
      - db
    env_file:
      - .web.env
