spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties.hibernate.format_sql: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driverClassName: org.h2.Driver

logging.level.org.hibernate:
  SQL: DEBUG
  type.descriptor.sql.BasicBinder: TRACE