spring:
  application:
    name: examen-api
  jackson:
    serialization:
      write-dates-as-timestamps: false
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
      url: jdbc:mysql://host.docker.internal:3306/payments?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      username: root
      password: sasa

server:
  port: 8080
  servlet:
    context-path: '/payments'

logging:
  file:
    name: logs/application.log
---
