INSERT INTO cliente (id, nombre, apellido, email) VALUES(1, 'Mateo', 'Calcagno', 'calcagno.mateo@gmail.com' );
INSERT INTO cliente (id, nombre, apellido, email) VALUES(2, 'Maximiliano', 'Soria', 'maxi.soria@gmail.com' );
INSERT INTO cliente (id, nombre, apellido, email) VALUES(3, 'Lucas', 'Monje', 'lu-monje@gmail.com' );
INSERT INTO cliente (id, nombre, apellido, email) VALUES(4, 'Nicolas', 'Barraza', 'nico.carp@hotmail.com' );
INSERT INTO cliente (id, nombre, apellido, email) VALUES(5, 'Carlos', 'Aires', 'airesc@yahoo.com.ar' );
INSERT INTO cliente (id, nombre, apellido, email) VALUES(6, 'Marcelo', 'Sanchez', 'eduardo.sanchez@gmail.com' );
INSERT INTO cliente (id, nombre, apellido, email) VALUES(7, 'Nahuel', 'Hualpa', 'nahuel-hualpa@outlook.com' );
INSERT INTO cliente (id, nombre, apellido, email) VALUES(8, 'Esteban', 'Slobodianik', 'slobodianik_esteban@hotmail.com' );
INSERT INTO cliente (id, nombre, apellido, email) VALUES(9, 'Kevin', 'Hidalgo', 'hidalgo.kevin@gmail.com' );
INSERT INTO cliente (id, nombre, apellido, email) VALUES(10, 'Raul', 'Charquero', 'raulchar@yahoo.com.ar' );
INSERT INTO vendedor(id, nombre, apellido, email) VALUES(1, 'Daniel', 'Lambdan', 'daniel-lambdan@gmail.com');
INSERT INTO vendedor(id, nombre, apellido, email) VALUES(2, 'Yoel', 'Martellini', 'martellini.yoel@hotmail.com');
INSERT INTO vendedor(id, nombre, apellido, email) VALUES(3, 'Nicolas', 'Ramirez', 'ramireznico@yahoo.com.ar');
INSERT INTO vendedor(id, nombre, apellido, email) VALUES(4, 'Laura', 'Gomez', 'lauri.gomez@yahoo.com.ar');
INSERT INTO vendedor(id, nombre, apellido, email) VALUES(5, 'Alicia', 'Lopez', 'ali-lopez@hotmail.com');
INSERT INTO vendedor(id, nombre, apellido, email) VALUES(6, 'Lorena', 'Martinez', 'lorena.martinez@outlook.com');
INSERT INTO vendedor(id, nombre, apellido, email) VALUES(7, 'Karina', 'Nanda', 'karina_nanda@hotmail.com');
INSERT INTO vendedor(id, nombre, apellido, email) VALUES(8, 'Maria', 'Estepa', 'estepa.maria@yahoo.com.ar');
INSERT INTO vendedor(id, nombre, apellido, email) VALUES(9, 'Martin', 'Cresmani', 'tincho.cresmani@hotmail.com');
INSERT INTO vendedor(id, nombre, apellido, email) VALUES(10, 'Daiana', 'Rios', 'dai_rios@yahoo.com.ar');
INSERT INTO producto(id, nombre, descripcion, precio) VALUES(1, 'Anteojos', 'Anteojos reflex para sol.', '100');
INSERT INTO producto(id, nombre, descripcion, precio) VALUES(2, 'Antonio Banderas Blue', 'Perfume para hombre.', '850');
INSERT INTO producto(id, nombre, descripcion, precio) VALUES(3, 'Reloj Eston', 'Reloj Eston de pulsera de metal.', '1200');
INSERT INTO producto(id, nombre, descripcion, precio) VALUES(4, 'Celular Samsung', 'Celular Samsung s8 de 4GB de ram, 3.68 GHz y 32GBs de espacio.', '4300');
INSERT INTO producto(id, nombre, descripcion, precio) VALUES(5, 'Pava electrica', 'Pava electrica de 30 revoluciones.', '800');
INSERT INTO producto(id, nombre, descripcion, precio) VALUES(6, 'Termo', 'Termo Nicau de color rojo de 2 litros.', '1100');
INSERT INTO producto(id, nombre, descripcion, precio) VALUES(7, 'Cargador Huawei', 'Cargador de 120v de Huawei.', '930');
INSERT INTO producto(id, nombre, descripcion, precio) VALUES(8, 'Microondas Atma', 'Microondas horno marca Atma.', '3560');
INSERT INTO producto(id, nombre, descripcion, precio) VALUES(9, 'Heladera Samsung', 'Heladera inteligente con conexion a wifi.', '8900');
INSERT INTO producto(id, nombre, descripcion, precio) VALUES(10, 'Freezer', 'Freezer HP 5 frios.', '3400');