CREATE TABLE CLIENTE(
	ID_CLIENTE BIGINT AUTO_INCREMENT PRIMARY KEY,
	NUM_IDENT VARCHAR(8),
	NOMBRE VARCHAR(50),
	APELLIDO VARCHAR(50),
	DIRECCION VARCHAR (80),
	EMAIL VARCHAR(50),
	TELEFONO VARCHAR(20),
	FECHA_A  TIMESTAMP,
	FECHA_M TIMESTAMP
); 
CREATE INDEX IDX_CLIENTE_NUM_IDENT ON CLIENTE(NUM_IDENT);
ALTER TABLE CLIENTE ADD CONSTRAINT UNQ_CLIENTE_NUM_IDENT UNIQUE(NUM_IDENT);

CREATE TABLE VENDEDOR(
	ID_VENDEDOR BIGINT AUTO_INCREMENT PRIMARY KEY,
	NUM_IDENT VARCHAR(8),
	CODIGO VARCHAR(8),
	NOMBRE VARCHAR(50),
	APELLIDO VARCHAR(50),
	EMAIL VARCHAR(50),
	TELEFONO VARCHAR(20),
	FECHA_A  TIMESTAMP,
	FECHA_M TIMESTAMP
);
CREATE INDEX IDX_VENDEDOR_CODIGO ON VENDEDOR(CODIGO);
ALTER TABLE VENDEDOR ADD CONSTRAINT UNQ_VENDEDOR_NUM_IDENT UNIQUE(NUM_IDENT);
ALTER TABLE VENDEDOR ADD CONSTRAINT UNQ_VENDEDOR_CODIGO UNIQUE(CODIGO);


CREATE TABLE PRODUCTO(
	ID_PRODUCTO BIGINT AUTO_INCREMENT PRIMARY KEY,
	CODIGO VARCHAR(6),
	DESCRIPCION VARCHAR(50),
	CANTIDAD INT,
	PRECIO DECIMAL,
	FECHA_A  TIMESTAMP,
	FECHA_M TIMESTAMP
);
CREATE INDEX IDX_PRODUCTO_CODIGO ON PRODUCTO(CODIGO);
ALTER TABLE PRODUCTO ADD CONSTRAINT UNQ_PRODUCTO_CODIGO UNIQUE(CODIGO);


CREATE TABLE FACTURA(
	ID_FACTURA BIGINT AUTO_INCREMENT PRIMARY KEY,	
	ID_CLIENTE BIGINT NOT NULL,
	ID_VENDEDOR BIGINT NOT NULL,
	CODIGO VARCHAR (6),
	FECHA DATE NOT NULL, 
	TOTAL DECIMAL NOT NULL ,
	ESTADO BOOLEAN,	
	FECHA_A  TIMESTAMP,
	FECHA_M TIMESTAMP
);
ALTER TABLE FACTURA ADD FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE);
ALTER TABLE FACTURA ADD FOREIGN KEY (ID_VENDEDOR) REFERENCES VENDEDOR(ID_VENDEDOR);
ALTER TABLE FACTURA ADD CONSTRAINT UNQ_FACTURA_CODIGO UNIQUE(CODIGO);
CREATE INDEX IDX_FACTURA_FECHA ON FACTURA(FECHA);
CREATE INDEX IDX_FACTURA_ID_VENDEDOR ON FACTURA(ID_VENDEDOR);
CREATE INDEX IDX_FACTURA_CODIGO ON FACTURA(CODIGO);
CREATE INDEX IDX_FACTURA_ESTADO ON FACTURA(ESTADO);


CREATE TABLE FACTURA_DETALLE(
	ID_FDETALLE BIGINT AUTO_INCREMENT PRIMARY KEY,
	FACTURA_ID_FACTURA BIGINT NOT NULL,
	ID_PRODUCTO BIGINT NOT NULL,
	CANTIDAD BIGINT NOT NULL, 	
	SUBTOTAL DECIMAL NOT NULL,
	FECHA_A  TIMESTAMP,
	FECHA_M TIMESTAMP
);
ALTER TABLE FACTURA_DETALLE ADD FOREIGN KEY (FACTURA_ID_FACTURA) REFERENCES FACTURA(ID_FACTURA);
ALTER TABLE FACTURA_DETALLE ADD FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO(ID_PRODUCTO);
CREATE INDEX IDX_FD_ID_FACTURA ON FACTURA(ID_FACTURA);