spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
      url: jdbc:mysql://127.0.0.1:3306/payments?zeroDateTimeBehavior=convertToNull
      username: root
      password: password

      h2:
        console:
          enabled: true
          path: /h2
        datasource:
          url: jdbc:h2:file:~/payments
          username: root
          password: password
          driverClassName: org.h2.Driver

server:
  port: 8080
  servlet:
    context-path: '/payments'
logging:
  path: ../../logs
  file: ${project.name}
  config:
    name: logback-spring.xml
    path: ${logging.path}/${logging.config.name}
---
